"""Serve REST route -> equivalent CLI command, for comparable telemetry.

Keyed by (HTTP method, route path template) exactly as FastAPI exposes it
(``route.path`` / the OpenAPI path). The value is the CLI command string the
route mirrors, so a serve event and a CLI event for the same operation share
one ``command`` (only the ``interface`` differs). An empty string means the
route has no CLI equivalent (serve-only or infra); the middleware still logs
it under a route-derived label.

Exhaustive by contract: the key set equals the serve route set exactly. Enforced
by tests/test_serve_telemetry.py::test_command_map_matches_every_route_exactly --
a route added, removed, or renamed fails CI, so the interfaces never diverge.
"""

SERVE_COMMAND_MAP: dict[tuple[str, str], str] = {
    ("DELETE", "/agents/{task_id}"): "agent delete",
    ("DELETE", "/branches/{project}/metadata/{metadata_id}"): "branch metadata-delete",
    ("DELETE", "/branches/{project}/{branch_id}"): "branch delete",
    ("DELETE", "/configs/{project}/{component_id}/{config_id}"): "config delete",
    (
        "DELETE",
        "/configs/{project}/{component_id}/{config_id}/metadata/{metadata_id}",
    ): "config delete-metadata",
    ("DELETE", "/configs/{project}/{component_id}/{config_id}/rows/{row_id}"): "config row-delete",
    ("DELETE", "/configs/{project}/{component_id}/{config_id}/variables"): "config variables-clear",
    ("DELETE", "/data-apps/{project}/{app_id}"): "data-app delete",
    ("DELETE", "/flows/{project}/{config_id}"): "flow delete",
    ("DELETE", "/flows/{project}/{config_id}/schedule"): "flow schedule-remove",
    ("DELETE", "/notifications/{project}/{subscription_id}"): "notification delete",
    ("DELETE", "/projects/{alias}"): "project remove",
    ("DELETE", "/semantic-layer/items/{kind}/{name}"): "",
    ("DELETE", "/semantic-layer/models/{model}"): "semantic-layer model delete",
    (
        "DELETE",
        "/semantic-layer/reference-data/{record_id}",
    ): "semantic-layer reference-data delete",
    ("DELETE", "/storage/buckets/{project}"): "storage delete-bucket",
    ("DELETE", "/storage/columns/{project}/{table_id}"): "storage delete-column",
    ("DELETE", "/storage/files/{project}"): "storage file-delete",
    ("DELETE", "/storage/snapshots/{project}"): "storage snapshot-delete",
    ("DELETE", "/storage/tables/{project}"): "storage delete-table",
    ("DELETE", "/workspaces/{project}/{workspace_id}"): "workspace delete",
    ("GET", "/agents"): "agent list",
    ("GET", "/agents/cron/preview"): "agent cron-preview",
    ("GET", "/agents/{task_id}"): "agent show",
    ("GET", "/agents/{task_id}/runs"): "agent runs",
    ("GET", "/agents/{task_id}/runs/{run_id}"): "agent run-detail",
    ("GET", "/agents/{task_id}/runs/{run_id}/events"): "agent run-events",
    ("GET", "/auth/projects"): "",
    ("GET", "/auth/status"): "auth status",
    ("GET", "/billing/credits"): "billing credits",
    ("GET", "/branches"): "branch list",
    ("GET", "/branches/{project}/merge-url"): "branch merge",
    ("GET", "/branches/{project}/metadata"): "branch metadata-list",
    ("GET", "/branches/{project}/metadata/{key}"): "branch metadata-get",
    ("GET", "/changelog"): "changelog",
    ("GET", "/components"): "component list",
    ("GET", "/components/{component_id}"): "component detail",
    ("GET", "/configs"): "config list",
    ("GET", "/configs/examples/{component_id}"): "config examples",
    ("GET", "/configs/search"): "config search",
    ("GET", "/configs/trash/{project}"): "config trash-list",
    ("GET", "/configs/{project}/{component_id}/{config_id}"): "config detail",
    ("GET", "/configs/{project}/{component_id}/{config_id}/metadata"): "config metadata-list",
    ("GET", "/configs/{project}/{component_id}/{config_id}/metadata/{key}"): "config get-metadata",
    ("GET", "/configs/{project}/{component_id}/{config_id}/oauth-url"): "config oauth-url",
    ("GET", "/configs/{project}/{component_id}/{config_id}/state"): "config state-get",
    ("GET", "/configs/{project}/{component_id}/{config_id}/variables"): "config variables-get",
    ("GET", "/data-apps"): "data-app list",
    ("GET", "/data-apps/{project}/{app_id}"): "data-app detail",
    ("GET", "/data-apps/{project}/{app_id}/git-repo"): "data-app git-repo",
    ("GET", "/data-apps/{project}/{app_id}/git-repo/credentials"): "data-app git-credentials",
    ("GET", "/data-apps/{project}/{app_id}/logs"): "data-app logs",
    ("GET", "/data-apps/{project}/{app_id}/password"): "data-app password",
    ("GET", "/data-apps/{project}/{app_id}/runs"): "data-app runs",
    ("GET", "/data-apps/{project}/{app_id}/secrets"): "data-app secrets-list",
    ("GET", "/data-apps/{project}/{app_id}/secrets/{key}"): "data-app secrets-get",
    ("GET", "/dev-portal/apps"): "dev-portal list",
    ("GET", "/dev-portal/apps/{app}"): "dev-portal get",
    ("GET", "/doctor"): "doctor",
    ("GET", "/feature/{project}/list"): "feature list",
    ("GET", "/feature/{project}/project-show"): "feature project-show",
    ("GET", "/feature/{project}/user-show"): "feature user-show",
    ("GET", "/flows"): "flow list",
    ("GET", "/flows/examples"): "flow examples",
    ("GET", "/flows/{project}/schema"): "flow schema",
    ("GET", "/flows/{project}/{config_id}"): "flow detail",
    ("GET", "/flows/{project}/{config_id}/schedules"): "",
    ("GET", "/flows/{project}/{config_id}/triggers"): "flow triggers",
    ("GET", "/health/auth-info"): "",
    ("GET", "/health/ping"): "",
    ("GET", "/jobs"): "job list",
    ("GET", "/jobs/{project}/{job_id}"): "job detail",
    ("GET", "/jobs/{project}/{job_id}/stream"): "job detail",
    ("GET", "/kai/chat/{chat_id}"): "kai chat-detail",
    ("GET", "/kai/history"): "kai history",
    ("GET", "/kai/ping"): "kai ping",
    ("GET", "/kai/preflight"): "kai preflight",
    ("GET", "/lineage/browser"): "lineage server",
    ("GET", "/lineage/data"): "",
    ("GET", "/lineage/edges"): "sharing edges",
    ("GET", "/lineage/info"): "lineage info",
    ("GET", "/lineage/mermaid"): "",
    ("GET", "/lineage/walk"): "",
    ("GET", "/members/{project}"): "project member-list",
    ("GET", "/members/{project}/invitations"): "project invitation-list",
    ("GET", "/notifications"): "notification list",
    ("GET", "/notifications/{project}/{subscription_id}"): "notification detail",
    ("GET", "/projects"): "project list",
    ("GET", "/projects/current"): "project current",
    ("GET", "/projects/status"): "project status",
    ("GET", "/projects/{alias}/description"): "project description-get",
    ("GET", "/projects/{alias}/info"): "project info",
    ("GET", "/schedules"): "schedule list",
    ("GET", "/schedules/find/query"): "schedule find",
    ("GET", "/schedules/{project}/{schedule_id}"): "schedule detail",
    ("GET", "/search"): "search",
    ("GET", "/semantic-layer/export"): "semantic-layer export",
    ("GET", "/semantic-layer/get-context"): "semantic-layer get-context",
    ("GET", "/semantic-layer/models"): "semantic-layer model list",
    ("GET", "/semantic-layer/reference-data"): "semantic-layer reference-data list",
    ("GET", "/semantic-layer/reference-data/{record_id}"): "semantic-layer reference-data get",
    ("GET", "/semantic-layer/schema"): "semantic-layer schema",
    ("GET", "/semantic-layer/search-context"): "semantic-layer search-context",
    ("GET", "/semantic-layer/show"): "semantic-layer show",
    ("GET", "/semantic-layer/validate"): "semantic-layer validate",
    ("GET", "/sharing"): "sharing list",
    ("GET", "/sharing/edges"): "sharing edges",
    ("GET", "/storage/buckets"): "storage buckets",
    ("GET", "/storage/buckets/{project}/{bucket_id}"): "storage bucket-detail",
    ("GET", "/storage/files"): "storage files",
    ("GET", "/storage/files/{project}/{file_id}"): "storage file-detail",
    ("GET", "/storage/files/{project}/{file_id}/download"): "storage file-download",
    ("GET", "/storage/snapshot-detail/{project}/{snapshot_id}"): "storage snapshot-detail",
    ("GET", "/storage/snapshots/{project}/{table_id}"): "storage snapshots",
    ("GET", "/storage/table-detail/{project}/{table_id}"): "storage table-detail",
    ("GET", "/storage/table-download/{project}/{table_id}"): "storage download-table",
    ("GET", "/storage/table-preview/{project}/{table_id}"): "",
    ("GET", "/storage/tables"): "storage tables",
    ("GET", "/stream/{project}/detail"): "stream detail",
    ("GET", "/stream/{project}/list"): "stream list",
    ("GET", "/token/list"): "token list",
    ("GET", "/token/{project}/list"): "token list",
    ("GET", "/transformations/{project}/{config_id}"): "transformation show",
    ("GET", "/ui-config"): "",
    ("GET", "/version"): "version",
    ("GET", "/workspaces"): "workspace list",
    ("GET", "/workspaces/{project}/{workspace_id}"): "workspace detail",
    ("PATCH", "/agents/{task_id}"): "agent update",
    ("PATCH", "/data-apps/{project}/{app_id}"): "data-app update",
    ("PATCH", "/configs/{project}/{component_id}/{config_id}"): "config update",
    ("PATCH", "/configs/{project}/{component_id}/{config_id}/rows/{row_id}"): "config row-update",
    ("PATCH", "/flows/{project}/{config_id}"): "flow update",
    ("PATCH", "/projects/{alias}"): "project edit",
    ("PATCH", "/transformations/{project}/{config_id}"): "transformation edit",
    ("POST", "/agents"): "agent create",
    ("POST", "/agents/prompt/improve"): "agent prompt-improve",
    ("POST", "/agents/prompt/improve/stream"): "agent prompt-improve",
    ("POST", "/agents/test"): "agent test",
    ("POST", "/agents/test/stream"): "agent test",
    ("POST", "/agents/{task_id}/run"): "agent run",
    ("POST", "/agents/{task_id}/run/stream"): "agent run",
    ("POST", "/ai/chat/stream"): "",
    ("POST", "/auth/register-projects"): "auth register-projects",
    ("POST", "/branches/{project}"): "branch create",
    ("POST", "/branches/{project}/reset"): "branch reset",
    ("POST", "/branches/{project}/use"): "branch use",
    ("POST", "/components/{component_id}/actions/{action}"): "component sync-action",
    ("POST", "/components/{component_id}/scaffold"): "config new",
    ("POST", "/configs/{project}/{component_id}"): "config new",
    ("POST", "/configs/{project}/{component_id}/{config_id}/clone"): "config clone",
    ("POST", "/configs/{project}/{component_id}/{config_id}/folder"): "config set-folder",
    ("POST", "/configs/{project}/{component_id}/{config_id}/rename"): "config rename",
    ("POST", "/configs/{project}/{component_id}/{config_id}/restore"): "config restore",
    ("POST", "/configs/{project}/{component_id}/{config_id}/rows"): "config row-create",
    (
        "POST",
        "/configs/{project}/{component_id}/{config_id}/set-default-bucket",
    ): "config set-default-bucket",
    ("POST", "/data-apps/validate-repo"): "data-app validate-repo",
    ("POST", "/data-apps/{project}"): "data-app create",
    ("POST", "/data-apps/{project}/{app_id}/deploy"): "data-app deploy",
    (
        "POST",
        "/data-apps/{project}/{app_id}/git-repo/credentials",
    ): "data-app git-credentials-create",
    ("POST", "/data-apps/{project}/{app_id}/secrets/remove"): "data-app secrets-remove",
    ("POST", "/data-apps/{project}/{app_id}/start"): "data-app start",
    ("POST", "/data-apps/{project}/{app_id}/stop"): "data-app stop",
    ("POST", "/documentation/query"): "docs query",
    ("POST", "/encrypt/values"): "encrypt values",
    ("POST", "/feature/{project}/project-add"): "feature project-add",
    ("POST", "/feature/{project}/project-remove"): "feature project-remove",
    ("POST", "/feature/{project}/user-add"): "feature user-add",
    ("POST", "/feature/{project}/user-remove"): "feature user-remove",
    ("POST", "/flows/validate"): "flow validate",
    ("POST", "/flows/{project}"): "flow new",
    ("POST", "/flows/{project}/{config_id}/schedule"): "flow schedule",
    ("POST", "/jobs/{project}/run"): "job run",
    ("POST", "/jobs/{project}/terminate"): "job terminate",
    ("POST", "/kai/ask"): "kai ask",
    ("POST", "/kai/chat"): "kai chat",
    ("POST", "/lineage/build"): "lineage build",
    ("POST", "/lineage/show"): "lineage show",
    ("POST", "/members/{project}/invitations/cancel"): "project invitation-cancel",
    ("POST", "/members/{project}/invite"): "project invite",
    ("POST", "/members/{project}/remove"): "project member-remove",
    ("POST", "/members/{project}/set-role"): "project member-set-role",
    ("POST", "/notifications/{project}"): "notification create",
    (
        "POST",
        "/notifications/{project}/{subscription_id}/replace-recipient",
    ): "notification replace-recipient",
    ("POST", "/org/refresh"): "project refresh",
    ("POST", "/org/setup"): "org setup",
    ("POST", "/projects"): "project add",
    ("POST", "/projects/bulk-delete"): "project remove",
    ("POST", "/projects/use/{alias}"): "project use",
    ("POST", "/semantic-layer/build"): "semantic-layer build",
    ("POST", "/semantic-layer/diff"): "semantic-layer diff",
    ("POST", "/semantic-layer/import"): "semantic-layer import",
    ("POST", "/semantic-layer/items/{kind}"): "",
    ("POST", "/semantic-layer/models"): "semantic-layer model create",
    ("POST", "/semantic-layer/promote"): "semantic-layer promote",
    ("POST", "/semantic-layer/token/encrypt"): "semantic-layer token",
    ("POST", "/sharing/{project}/link"): "sharing link",
    ("POST", "/sharing/{project}/share"): "sharing share",
    ("POST", "/sharing/{project}/unlink/{bucket_id}"): "sharing unlink",
    ("POST", "/sharing/{project}/unshare/{bucket_id}"): "sharing unshare",
    ("POST", "/storage/buckets/{project}"): "storage create-bucket",
    ("POST", "/storage/buckets/{project}/{bucket_id}/describe"): "storage describe-bucket",
    ("POST", "/storage/columns/{project}/describe-migrate"): "storage describe-migrate",
    ("POST", "/storage/columns/{project}/{table_id}"): "storage add-column",
    ("POST", "/storage/columns/{project}/{table_id}/describe"): "storage describe-column",
    ("POST", "/storage/files/upload"): "storage file-upload",
    ("POST", "/storage/files/{project}/load-to-table"): "storage load-file",
    ("POST", "/storage/files/{project}/{file_id}/tag"): "storage file-tag",
    ("POST", "/storage/table-from-snapshot/{project}"): "storage table-from-snapshot",
    ("POST", "/storage/tables/{project}"): "storage create-table",
    ("POST", "/storage/tables/{project}/truncate"): "storage truncate-table",
    ("POST", "/storage/tables/{project}/upload"): "storage upload-table",
    ("POST", "/storage/tables/{project}/{table_id}/describe"): "storage describe-table",
    ("POST", "/storage/tables/{project}/{table_id}/pull"): "storage clone-table",
    ("POST", "/storage/tables/{project}/{table_id}/snapshots"): "storage snapshot-create",
    ("POST", "/storage/tables/{project}/{table_id}/swap"): "storage swap-tables",
    ("POST", "/stream/{project}/create-source"): "stream create-source",
    ("POST", "/stream/{project}/delete"): "stream delete",
    ("POST", "/token/{project}/create"): "token create",
    ("POST", "/token/{project}/delete"): "token delete",
    ("POST", "/token/{project}/refresh"): "token refresh",
    ("POST", "/transformations/{project}"): "transformation create",
    ("POST", "/workspaces/gc"): "workspace gc",
    ("POST", "/workspaces/sql/improve/stream"): "",
    ("POST", "/workspaces/{project}"): "workspace create",
    ("POST", "/workspaces/{project}/from-transformation"): "workspace from-transformation",
    ("POST", "/workspaces/{project}/{workspace_id}/load"): "workspace load",
    ("POST", "/workspaces/{project}/{workspace_id}/password"): "workspace password",
    ("POST", "/workspaces/{project}/{workspace_id}/query"): "workspace query",
    ("PUT", "/branches/{project}/metadata/{key}"): "branch metadata-set",
    ("PUT", "/configs/{project}/{component_id}/{config_id}/metadata/{key}"): "config set-metadata",
    ("PUT", "/configs/{project}/{component_id}/{config_id}/state"): "config state-set",
    ("PUT", "/configs/{project}/{component_id}/{config_id}/variables"): "config variables-set",
    ("PUT", "/data-apps/{project}/{app_id}/secrets"): "data-app secrets-set",
    ("PUT", "/projects/{alias}/description"): "project description-set",
    ("PUT", "/semantic-layer/items/{kind}/{name}"): "",
    ("PUT", "/semantic-layer/reference-data"): "semantic-layer reference-data set",
}
